name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'build_docker.sh'
      - 'requirements.txt'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Dockerfile'
      - 'build_docker.sh'
      - 'requirements.txt'
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag larndsim:latest
